[build-system]
requires = [
    "setuptools>=65",
    "cmake>=3.21",
    "mypy>=1.8.0",
    "pytest>=6.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ""
testpaths = ["tests/"]
