name: macOS Builds

on: push

jobs:
  macos_build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python Dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools wheel

    - name: Build Python Wheel
      shell: bash
      run: |
        python3 setup.py clean --all
        python3 setup.py bdist_wheel
