name: Linux Builds

on:
  push:
    branches:
      - '**'
    paths:
      - "**/workflows/build_linux.yml"
      - "**/cmake/**"
      - "**/JUCE/**"
      - "**/modules/**"
      - "**/tests/**"
      - ".gitmodules"
      - "CMakeLists.txt"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build cp${{matrix.python}}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        include:
        - { os: ubuntu-latest, python: 310, platform_id: manylinux_x86_64, cibw_archs: x86_64 }
        - { os: ubuntu-latest, python: 310, platform_id: manylinux_aarch64, cibw_archs: aarch64 }

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup and install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS: ${{matrix.cibw_archs}}
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_TEST_SKIP: "*-manylinux_aarch64"

      - name: Store failures artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compare-data
          path: |
            ./wheelhouse/compare_data/
            !./wheelhouse/compare_data/.gitignore
          if-no-files-found: ignore
          retention-days: 5
          compression-level: 0
          overwrite: true
