name: Linux Builds

on:
  push

jobs:
  linux_build:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Linux dependencies
      run: |
        sudo apt-get install zlib1g-dev libpng-dev libcurl3-dev libcurl4-openssl-dev libssl-dev
        sudo apt-get install libasound2-dev libfreetype6-dev libxcomposite-dev libxcursor-dev
        sudo apt-get install libxinerama-dev libxrandr-dev libxrender-dev libx11-dev
        sudo apt-get install x11proto-randr-dev x11proto-render-dev x11proto-xinerama-dev
        sudo apt-get install freeglut3-dev mesa-common-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools wheel

    - name: Build Python Wheel
      shell: bash
      run: |
        python3 setup.py clean --all
        python3 setup.py bdist_wheel
