name: macOS Builds

on:
  push:
    paths:
      - "**/workflows/build_macos.yml"
      - "**/cmake/**"
      - "**/JUCE/**"
      - "**/modules/**"
      - "**/tests/**"
      - ".gitmodules"
      - "CMakeLists.txt"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-macos:
    name: Build cp${{matrix.python}}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        include:
        - { os: macos-latest, python: 310, platform_id: macosx_universal2, cibw_archs: universal2 }

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup and install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS: ${{matrix.cibw_archs}}
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_TEST_SKIP: "*-macosx_universal2:arm64"

      - name: Store failures artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compare-data
          path: |
            tests/compare_data/
            !tests/compare_data/.gitignore
          if-no-files-found: ignore
          retention-days: 5
          compression-level: 0
          overwrite: true
