name: Release Wheels

on:
  release:
    types: [published, edited]

jobs:
  linux_build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Linux dependencies
      run: |
        sudo apt-get install zlib1g-dev libpng-dev libcurl3-dev libcurl4-openssl-dev libssl-dev
        sudo apt-get install libasound2-dev libfreetype6-dev libxcomposite-dev libxcursor-dev
        sudo apt-get install libxinerama-dev libxrandr-dev libxrender-dev libx11-dev
        sudo apt-get install x11proto-randr-dev x11proto-render-dev x11proto-xinerama-dev
        sudo apt-get install freeglut3-dev mesa-common-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools wheel twine auditwheel auditwheel-symbols

    - name: Build Python Wheel
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      shell: bash
      run: |
        python3 setup.py clean --all
        python3 setup.py bdist_wheel --plat-name linux_x86_64
        auditwheel show dist/*.whl
        auditwheel repair --plat manylinux2014_x86_64 --strip -L data -w dist/ dist/*.whl
        auditwheel-symbols --manylinux 2014 dist/*-manylinux*.whl
        python3 -m twine upload --repository-url ${{ secrets.TWINE_REPOSITORY }} dist/*-manylinux*.whl


  macos_build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools wheel twine

    - name: Build Python Wheel
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      shell: bash
      run: |
        python3 setup.py clean --all
        python3 setup.py bdist_wheel
        python3 -m twine upload --repository-url ${{ secrets.TWINE_REPOSITORY }} dist/*.whl


  windows_build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build Python Wheel
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      shell: bash
      run: |
        python setup.py clean --all
        python setup.py bdist_wheel
        python -m twine upload --repository-url ${{ secrets.TWINE_REPOSITORY }} dist/*.whl
