name: Test Deploy

on:
  push:
    branches:
      - kraken/github_actions

jobs:
  build-wheels:
    name: Build wheel for ${{ matrix.build }}

    runs-on: ${{ matrix.os }}
    continue-on-error: false

    #if: github.event_name == 'release' && github.event.action == 'published'

    strategy:
      matrix:
        include:
        - { os: macos-latest, build: cp36-macosx_x86_64 }
        - { os: macos-latest, build: cp37-macosx_x86_64 }
        - { os: macos-latest, build: cp38-macosx_x86_64 }
        - { os: macos-latest, build: cp39-macosx_x86_64 }
        - { os: macos-latest, build: cp310-macosx_x86_64 }
        - { os: macos-latest, build: cp38-macosx_universal2 }
        - { os: macos-latest, build: cp39-macosx_universal2 }
        - { os: macos-latest, build: cp310-macosx_universal2 }
        - { os: macos-latest, build: pp37-macosx_x86_64 }
        - { os: macos-latest, build: pp38-macosx_x86_64 }
        - { os: windows-latest, build: cp36-win_amd64 }
        - { os: windows-latest, build: cp37-win_amd64 }
        - { os: windows-latest, build: cp38-win_amd64 }
        - { os: windows-latest, build: cp39-win_amd64 }
        - { os: windows-latest, build: cp310-win_amd64 }
        - { os: windows-latest, build: pp37-win_amd64 }
        - { os: windows-latest, build: pp38-win_amd64 }
        - { os: ubuntu-latest, build: cp36-manylinux_x86_64 }
        - { os: ubuntu-latest, build: cp36-manylinux_aarch64 }
        - { os: ubuntu-latest, build: cp37-manylinux_x86_64 }
        - { os: ubuntu-latest, build: cp37-manylinux_aarch64 }
        - { os: ubuntu-latest, build: cp38-manylinux_x86_64 }
        - { os: ubuntu-latest, build: cp38-manylinux_aarch64 }
        - { os: ubuntu-latest, build: cp39-manylinux_x86_64 }
        - { os: ubuntu-latest, build: cp39-manylinux_aarch64 }
        - { os: ubuntu-latest, build: cp310-manylinux_x86_64 }
        - { os: ubuntu-latest, build: cp310-manylinux_aarch64 }
        - { os: ubuntu-latest, build: pp37-manylinux_x86_64 }
        - { os: ubuntu-latest, build: pp37-manylinux_aarch64 }
        - { os: ubuntu-latest, build: pp38-manylinux_x86_64 }
        - { os: ubuntu-latest, build: pp38-manylinux_aarch64 }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel>=2.0.0a4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_ARCHS: auto64
          CIBW_ARCHS_LINUX: auto64 aarch64 # Useful for building linux images with Apple Silicon
          CIBW_ARCHS_MACOS: x86_64 universal2 # Support Apple Silicon
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: pip install auditwheel-symbols && (auditwheel repair -w {dest_dir} {wheel} || auditwheel-symbols --manylinux 2014 {wheel})
          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y \
              zlib-devel \
              openssl-devel \
              freetype-devel \
              freeglut-devel \
              alsa-lib-devel \
              mesa-common-devel \
              xorg-x11-proto-devel \
              xorg-x11-proto-devel \
              libcurl-devel \
              libpng-devel \
              libX11-devel \
              libXcursor-devel \
              libXrandr-devel \
              libXinerama-devel \
              libXrender-devel \
              libXcomposite-devel \
              libXinerama-devel \
              libXcursor-devel
          CIBW_TEST_SKIP: "*manylinux* *pp* *-macosx_universal2:arm64"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl


  upload-pypi:
    name: "Upload wheels to PyPI"

    needs: [build-wheels]
    runs-on: ubuntu-latest

    if: ${{ false }}
    #if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
