name: Test Deploy

on: push
#on:
#  release:
#    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    # if: github.event_name == 'release' && github.event.action == 'published'

    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: macos-latest, python: 38, platform_id: macosx_universal2 }
        - { os: macos-latest, python: 39, platform_id: macosx_universal2 }
        - { os: macos-latest, python: 310, platform_id: macosx_universal2 }
        - { os: macos-latest, python: 311, platform_id: macosx_universal2 }
        - { os: macos-latest, python: 312, platform_id: macosx_universal2 }
        #- { os: windows-latest, python: 38, platform_id: win_amd64 }
        #- { os: windows-latest, python: 39, platform_id: win_amd64 }
        #- { os: windows-latest, python: 310, platform_id: win_amd64 }
        #- { os: windows-latest, python: 311, platform_id: win_amd64 }
        #- { os: windows-latest, python: 312, platform_id: win_amd64 }
        #- { os: ubuntu-latest, python: 38, platform_id: manylinux_x86_64 }
        # - { os: ubuntu-latest, python: 38, platform_id: manylinux_aarch64 }
        #- { os: ubuntu-latest, python: 39, platform_id: manylinux_x86_64 }
        # - { os: ubuntu-latest, python: 39, platform_id: manylinux_aarch64 }
        #- { os: ubuntu-latest, python: 310, platform_id: manylinux_x86_64 }
        # - { os: ubuntu-latest, python: 310, platform_id: manylinux_aarch64 }
        #- { os: ubuntu-latest, python: 311, platform_id: manylinux_x86_64 }
        # - { os: ubuntu-latest, python: 311, platform_id: manylinux_aarch64 }
        #- { os: ubuntu-latest, python: 312, platform_id: manylinux_x86_64 }
        # - { os: ubuntu-latest, python: 312, platform_id: manylinux_aarch64 }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: all
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: pip install auditwheel-symbols && (auditwheel repair -w {dest_dir} {wheel} || auditwheel-symbols --manylinux 2014 {wheel})
          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y \
              zlib-devel \
              openssl-devel \
              freetype-devel \
              freeglut-devel \
              alsa-lib-devel \
              mesa-libGL-devel \
              xorg-x11-proto-devel \
              xorg-x11-proto-devel \
              libcurl-devel \
              libpng-devel \
              libX11-devel \
              libXcursor-devel \
              libXrandr-devel \
              libXinerama-devel \
              libXrender-devel \
              libXcomposite-devel \
              libXinerama-devel \
              libXcursor-devel
          CIBW_TEST_SKIP: "*manylinux* *pp* *-macosx_universal2:arm64"

      - uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: ./wheelhouse/*.whl

  upload-pypi:
    name: "Upload wheels to PyPI"

    needs: [build-wheels]
    runs-on: ubuntu-latest

    #if: github.event_name == 'release' && github.event.action == 'published'
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

